[global]
Name = Elite_Dev
UIName = elite
Description = Dawn of War II: Elite
ModVersion = 2.11
ModFolder = elite
UCSBaseIndex = 10000000

[attrib:common]
folder.01 = Elite\DataAttrib
folder.02 = GameAssets\DataAttrib
archive.01 = elite\Archives\Elite_attrib.sga
archive.02 = elite\Archives\Elite_Campaign_Attrib.sga
archive.03 = elite\Archives\GameAttrib_orig.sga

[sound:common]
folder.01 = Elite\Data\Sound
folder.02 = GameAssets\Data\Sound
archive.01 = elite\Archives\Elite_sound.sga
archive.02 = GameAssets\Archives\GameSoundContainers.sga
archive.03 = GameAssets\Archives\002_sound.sga
archive.04 = GameAssets\Archives\001_sound.sga
archive.05 = GameAssets\Archives\000_sound.sga
archive.06 = GameAssets\Archives\003_sound.sga

[sound:english]
folder.01 = GameAssets\Locale\English\Sound
archive.01 = elite\Archives\Elite_speech.sga
archive.02 = GameAssets\Locale\English\English_GameSpeechContainers.sga
archive.03 = GameAssets\Locale\English\English_002_speech_campaign.sga
archive.04 = GameAssets\Locale\English\English_002_speech.sga
archive.05 = GameAssets\Locale\English\English_001_speech_campaign.sga
archive.06 = GameAssets\Locale\English\English_001_speech.sga
archive.07 = GameAssets\Locale\English\English_000_speech_campaign.sga
archive.08 = GameAssets\Locale\English\English_000_speech.sga

[sound:french]
folder.01 = GameAssets\Locale\French\Sound
archive.01 = GameAssets\Locale\French\French_GameSpeechContainers.sga
archive.02 = GameAssets\Locale\French\French_002_speech_campaign.sga
archive.03 = GameAssets\Locale\French\French_002_speech.sga
archive.04 = GameAssets\Locale\French\French_001_speech_campaign.sga
archive.05 = GameAssets\Locale\French\French_001_speech.sga
archive.06 = GameAssets\Locale\French\French_000_speech_campaign.sga
archive.07 = GameAssets\Locale\French\French_000_speech.sga

[sound:german]
folder.01 = GameAssets\Locale\German\Sound
archive.01 = GameAssets\Locale\German\German_GameSpeechContainers.sga
archive.02 = GameAssets\Locale\German\German_002_speech_campaign.sga
archive.03 = GameAssets\Locale\German\German_002_speech.sga
archive.04 = GameAssets\Locale\German\German_001_speech_campaign.sga
archive.05 = GameAssets\Locale\German\German_001_speech.sga
archive.06 = GameAssets\Locale\German\German_000_speech_campaign.sga
archive.07 = GameAssets\Locale\German\German_000_speech.sga

[sound:russian]
folder.01 = GameAssets\Locale\Russian\Sound
archive.01 = GameAssets\Locale\Russian\Russian_GameSpeechContainers.sga
archive.02 = GameAssets\Locale\Russian\Russian_002_speech_campaign.sga
archive.03 = GameAssets\Locale\Russian\Russian_002_speech.sga
archive.04 = GameAssets\Locale\Russian\Russian_001_speech_campaign.sga
archive.05 = GameAssets\Locale\Russian\Russian_001_speech.sga
archive.06 = GameAssets\Locale\Russian\Russian_000_speech_campaign.sga
archive.07 = GameAssets\Locale\Russian\Russian_000_speech.sga

[sound:spanish]
folder.01 = GameAssets\Locale\Spanish\Sound
archive.01 = GameAssets\Locale\Spanish\Spanish_GameSpeechContainers.sga
archive.02 = GameAssets\Locale\Spanish\Spanish_002_speech_campaign.sga
archive.03 = GameAssets\Locale\Spanish\Spanish_002_speech.sga
archive.04 = GameAssets\Locale\Spanish\Spanish_001_speech_campaign.sga
archive.05 = GameAssets\Locale\Spanish\Spanish_001_speech.sga
archive.06 = GameAssets\Locale\Spanish\Spanish_000_speech_campaign.sga
archive.07 = GameAssets\Locale\Spanish\Spanish_000_speech.sga

[sound:italian]
folder.01 = GameAssets\Locale\Italian\Sound
archive.01 = GameAssets\Locale\Italian\English_GameSpeechContainers.sga
archive.02 = GameAssets\Locale\Italian\English_002_speech_campaign.sga
archive.03 = GameAssets\Locale\Italian\English_002_speech.sga
archive.04 = GameAssets\Locale\Italian\English_001_speech_campaign.sga
archive.05 = GameAssets\Locale\Italian\English_001_speech.sga
archive.06 = GameAssets\Locale\Italian\English_000_speech_campaign.sga
archive.07 = GameAssets\Locale\Italian\English_000_speech.sga

[sound:czech]
folder.01 = GameAssets\Locale\Czech\Sound
archive.01 = GameAssets\Locale\Czech\English_GameSpeechContainers.sga
archive.02 = GameAssets\Locale\Czech\English_002_speech_campaign.sga
archive.03 = GameAssets\Locale\Czech\English_002_speech.sga
archive.04 = GameAssets\Locale\Czech\English_001_speech_campaign.sga
archive.05 = GameAssets\Locale\Czech\English_001_speech.sga
archive.06 = GameAssets\Locale\Czech\English_000_speech_campaign.sga
archive.07 = GameAssets\Locale\Czech\English_000_speech.sga

[sound:polish]
folder.01 = GameAssets\Locale\Polish\Sound
archive.01 = GameAssets\Locale\Polish\English_GameSpeechContainers.sga
archive.02 = GameAssets\Locale\Polish\English_002_speech_campaign.sga
archive.03 = GameAssets\Locale\Polish\English_002_speech.sga
archive.04 = GameAssets\Locale\Polish\English_001_speech_campaign.sga
archive.05 = GameAssets\Locale\Polish\English_001_speech.sga
archive.06 = GameAssets\Locale\Polish\English_000_speech_campaign.sga
archive.07 = GameAssets\Locale\Polish\English_000_speech.sga

[sound:tchinese]
folder.01 = GameAssets\Locale\TChinese\Sound
archive.01 = GameAssets\Locale\TChinese\English_GameSpeechContainers.sga
archive.02 = GameAssets\Locale\TChinese\English_002_speech_campaign.sga
archive.03 = GameAssets\Locale\TChinese\English_002_speech.sga
archive.04 = GameAssets\Locale\TChinese\English_001_speech_campaign.sga
archive.05 = GameAssets\Locale\TChinese\English_001_speech.sga
archive.06 = GameAssets\Locale\TChinese\English_000_speech_campaign.sga
archive.07 = GameAssets\Locale\TChinese\English_000_speech.sga

[movies:common]
folder.01 = GameAssets\Data\Movies

[movies:english]
folder.01 = GameAssets\Locale\English\Movies

[movies:french]
folder.01 = GameAssets\Locale\French\Movies

[movies:german]
folder.01 = GameAssets\Locale\German\Movies

[movies:russian]
folder.01 = GameAssets\Locale\Russian\Movies

[movies:spanish]
folder.01 = GameAssets\Locale\Spanish\Movies

[movies:italian]
folder.01 = GameAssets\Locale\Italian\Movies

[movies:czech]
folder.01 = GameAssets\Locale\Czech\Movies

[movies:polish]
folder.01 = GameAssets\Locale\Polish\Movies

[movies:tchinese]
folder.01 = GameAssets\Locale\TChinese\Movies

[data:common]
folder.01 = Elite\Data
folder.02 = GameAssets\Data
archive.01 = elite\Archives\Elite_config.sga
archive.02 = elite\Archives\Elite_Data_01_Marine_Core.sga
archive.03 = elite\Archives\Elite_Data_02_Marine_Armour.sga
archive.04 = elite\Archives\Elite_Data_03_Orks_Core.sga
archive.05 = elite\Archives\Elite_Data_04_Orks_Wargear.sga
archive.06 = elite\Archives\Elite_Data_05_Eldar_Core.sga
archive.07 = elite\Archives\Elite_Data_06_Eldar_Armour.sga
archive.08 = elite\Archives\Elite_Data_07_Tyranid.sga
archive.09 = elite\Archives\Elite_Data_08_Chaos_Core.sga
archive.10 = elite\Archives\Elite_Data_09_Chaos_Armour.sga
archive.11 = elite\Archives\Elite_Data_10_IG_Core.sga
archive.12 = elite\Archives\Elite_Data_11_IG_Armour.sga
archive.13 = elite\Archives\Elite_Data_12_GK_Core.sga
archive.14 = elite\Archives\Elite_Data_13_GK_Wargear.sga
archive.15 = elite\Archives\Elite_Data_14_Necron.sga
archive.16 = elite\Archives\Elite_Data_15_FX.sga
archive.17 = elite\Archives\Elite_Data_16_Misc.sga
archive.18 = elite\Archives\Elite_Data_17_UI_Core.sga
archive.19 = elite\Archives\Elite_Data_18_UI_Maps.sga
archive.20 = elite\Archives\Elite_Data_19_Maps_01.sga
archive.21 = elite\Archives\Elite_Data_20_Maps_02.sga
archive.22 = elite\Archives\Elite_Campaign_Data.sga
archive.23 = GameAssets\Archives\005_multiplayer.sga
archive.24 = GameAssets\Archives\005_data.sga
archive.25 = GameAssets\Archives\005_laststand.sga
archive.26 = GameAssets\Archives\004_campaign.sga
archive.27 = GameAssets\Archives\004_laststand.sga
archive.28 = GameAssets\Archives\004_multiplayer.sga
archive.29 = GameAssets\Archives\004_extra.sga
archive.30 = GameAssets\Archives\004_data.sga
archive.31 = GameAssets\Archives\003_campaign.sga
archive.32 = GameAssets\Archives\003_laststand.sga
archive.33 = GameAssets\Archives\003_multiplayer.sga
archive.34 = GameAssets\Archives\003_extra.sga
archive.35 = GameAssets\Archives\003_data.sga
archive.36 = GameAssets\Archives\002_campaign.sga
archive.37 = GameAssets\Archives\002_laststand.sga
archive.38 = GameAssets\Archives\002_multiplayer.sga
archive.39 = GameAssets\Archives\002_extra.sga
archive.40 = GameAssets\Archives\002_data.sga
archive.41 = GameAssets\Archives\001_campaign.sga
archive.42 = GameAssets\Archives\001_laststand.sga
archive.43 = GameAssets\Archives\001_multiplayer.sga
archive.44 = GameAssets\Archives\001_extra.sga
archive.45 = GameAssets\Archives\001_data.sga
archive.46 = GameAssets\Archives\000_campaign.sga
archive.47 = GameAssets\Archives\000_laststand.sga
archive.48 = GameAssets\Archives\000_multiplayer.sga
archive.49 = GameAssets\Archives\000_extra.sga
archive.50 = GameAssets\Archives\000_data.sga
